import type { Metadata } from "next";
import { MarketingNavbar } from "./youtube-video-summarizer/_components/marketing-navbar";

export const metadata: Metadata = {
  title: "AI Summarization Tool",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col">
      <div><MarketingNavbar /></div>
      {children}
    </div>
  );
}
